import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# ACONSYS
VASICONT_EXE_PATH = Path(os.environ["VASICONT_EXE_PATH"])
ACONSYS_PASSWORD = os.environ["ACONSYS_PASSWORD"]
ACONSYS_USER = os.environ["ACONSYS_USER"]
# VENTAS
INPUT_FILE_VENTAS = os.environ["INPUT_FILE_VENTAS"]
TEMPLATE_FILE_VENTAS = os.environ["TEMPLATE_FILE_VENTAS"]
OUTPUT_FILE_VENTAS = os.environ["OUTPUT_FILE_VENTAS"]
INPUT_DIR = os.environ["INPUT_DIR"]
OUPUT_DIR = os.environ["OUPUT_DIR"]

# CAPTCHA
API_KEY_2CAPTCHA = os.environ["2CAPTCHA_API_KEY"]

# OCR
RUTA_DOC = os.environ["RUTA_DOC"]

# OUTPUT FILE SUBIR VENTAS
OUTPUT_FILE_SUBIR_VENTAS = os.environ["OUTPUT_FILE_SUBIR_VENTAS"]
#OUTPUT_FILE_SUBIR_VENTAS_COPY = os.environ["OUTPUT_FILE_SUBIR_VENTAS_COPY"]

# IMPORTACIONES
IMPORTACIONES_EXE_PATH = Path(os.environ["IMPORTACIONES_EXE_PATH"])
IMPORTACIONES_USER = os.environ["IMPORTACIONES_USER"]
IMPORTACIONES_PASSWORD = os.environ["IMPORTACIONES_PASSWORD"]
IMPORTACIONES_PASSWORD = os.environ["IMPORTACIONES_PASSWORD"]
